### ISSUE TITLE
Documentação de Contexto - Objetivos e Justificativa

### ISSUE THREAD

**Issue by ytallobruno** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t4-pmv-ads-2024-1-e1-proj-fila-facil#9]

**Comment by diiegochaves** [comment]
# Titulo
*Negrito*
* Marcação 

entre outros .... 

Usei o readme.so para ter uma noção básica para realizar a tarefa proposta em grupo.
