### ISSUE TITLE
Criar um alerta no chat caso usuário não esteja logado

### ISSUE THREAD

**Issue by ytallobruno** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e1-proj-web-t4-pmv-ads-2024-1-e1-proj-fila-facil#98]

**Comment by gabrielroeder** [comment]
Podemos usar essa issue para criar uma validação de usuário logado em todas as páginas necessárias (praticamente todas, menos index.html, login.html e cadastro.html). Caso não estiver logado, redirecionar para a página `login.html`
